version: '3.7'
services:
  angermann:
    build: .
    image: bjornsolman/solman1980:spring-app
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongodb.host=mongodb
    depends_on:
      - mongodb
  mongodb:
    build: .
    image: mongo:5.0.3
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: