server:
  error:
    include-message: always
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-alias: laget
    key-store-password: xxx

spring:
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      database: laget
      port: 27017
      host: localhost

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
